
Showing logs for build [32mtrietlu-flask-jx-sample-pr-14-s-czzwj-2[0m stage [32mfrom-build-pack[0m and container [32mstep-credential-initializer-r9bkp[0m
{"level":"warn","ts":1581960185.5556314,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"ref: refs/heads/0.8.0-**-support-backwards-incompats\" is not a valid GitHub commit ID"}
{"level":"info","ts":1581960185.5558915,"logger":"fallback-logger","caller":"creds-init/main.go:40","msg":"Credentials initialized."}

Showing logs for build [32mtrietlu-flask-jx-sample-pr-14-s-czzwj-2[0m stage [32mfrom-build-pack[0m and container [32mstep-working-dir-initializer-6mnqw[0m
{"level":"warn","ts":1581960186.5508091,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/HEAD: no such file or directory"}
{"level":"info","ts":1581960186.5532458,"logger":"fallback-logger","caller":"bash/main.go:64","msg":"Successfully executed command \"sh -c mkdir -p /workspace/source\"; output "}

Showing logs for build [32mtrietlu-flask-jx-sample-pr-14-s-czzwj-2[0m stage [32mfrom-build-pack[0m and container [32mstep-place-tools[0m

Showing logs for build [32mtrietlu-flask-jx-sample-pr-14-s-czzwj-2[0m stage [32mfrom-build-pack[0m and container [32mstep-git-source-trietlu-flask-jx-sample-pr-14-s-czzwj-b5jxx[0m
{"level":"warn","ts":1581960192.6006308,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"ref: refs/heads/0.8.0-**-support-backwards-incompats\" is not a valid GitHub commit ID"}
{"level":"info","ts":1581960192.8866243,"logger":"fallback-logger","caller":"git/git.go:103","msg":"Successfully cloned https://github.com/*******/flask-**-sample.git @ master in path /workspace/source"}

Showing logs for build [32mtrietlu-flask-jx-sample-pr-14-s-czzwj-2[0m stage [32mfrom-build-pack[0m and container [32mstep-git-merge[0m
Using SHAs from PULL_REFS=master:e0bf971a3d9c07423089cdb60e61a661aadf0af1,14:0efb628db7aed22996755317ceb3179456f0dbf9
DEBUG: LC_ALL=C JX_LOG_LEVEL=error git fetch origin --unshallow 0efb628db7aed22996755317ceb3179456f0dbf9: e0bf971a3d9c07423089cdb60e61a661aadf0af1:
DEBUG: ran git fetch --unshallow origin 0efb628db7aed22996755317ceb3179456f0dbf9: e0bf971a3d9c07423089cdb60e61a661aadf0af1: in 
DEBUG: LC_ALL=C JX_LOG_LEVEL=error git branch
DEBUG: LC_ALL=C JX_LOG_LEVEL=error git checkout master
DEBUG: ran git checkout master in 
DEBUG: LC_ALL=C JX_LOG_LEVEL=error git reset --hard e0bf971a3d9c07423089cdb60e61a661aadf0af1
DEBUG: ran git reset --hard e0bf971a3d9c07423089cdb60e61a661aadf0af1 in 
DEBUG: LC_ALL=C JX_LOG_LEVEL=error git clean -fd .
DEBUG: ran clean --force -d . in 
DEBUG: LC_ALL=C JX_LOG_LEVEL=error git merge 0efb628db7aed22996755317ceb3179456f0dbf9
DEBUG: ran git merge 0efb628db7aed22996755317ceb3179456f0dbf9 in 
DEBUG: JX_LOG_LEVEL=error LC_ALL=C git log --format=%H%x1f%an%x1f%ae%x1f%cn%x1f%ce%x1f%s%n%b%x1e e0bf971a3d9c07423089cdb60e61a661aadf0af1..HEAD
Merged SHA 0efb628db7aed22996755317ceb3179456f0dbf9 with commit message 'Update flask_app.py' into base branch master
Merged SHA 881233f281dc01361dd6c978d61593e3bac130cd with commit message 'Update flask_app.py' into base branch master

Showing logs for build [32mtrietlu-flask-jx-sample-pr-14-s-czzwj-2[0m stage [32mfrom-build-pack[0m and container [32mstep-build-code-scan[0m
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip3 install --user` instead.
Collecting python-taint
  Downloading https://files.pythonhosted.org/packages/5c/79/5b70d3299cb7dea63e2b015651c5c7507d723911ff2837e104ebd7079491/python_taint-0.42-py3-none-any.whl (52kB)
Installing collected packages: python-taint
Successfully installed python-taint-0.42
No vulnerabilities found.

Showing logs for build [32mtrietlu-flask-jx-sample-pr-14-s-czzwj-2[0m stage [32mfrom-build-pack[0m and container [32mstep-build-python-unittest[0m

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK

Showing logs for build [32mtrietlu-flask-jx-sample-pr-14-s-czzwj-2[0m stage [32mfrom-build-pack[0m and container [32mstep-build-container-build[0m
[36mINFO[0m[0000] Downloading base image python:onbuild        
[36mINFO[0m[0000] Error while retrieving image from cache: getting file info: stat /workspace/sha256:43780a8431c53f4afd734ad795e03127c0c607337a60639c5903a51a03535c22: no such file or directory 
[36mINFO[0m[0000] Downloading base image python:onbuild        
[36mINFO[0m[0000] Executing 3 build triggers                   
[36mINFO[0m[0000] Using files from context: [/workspace/source/requirements.txt] 
[36mINFO[0m[0000] Checking for cached layer 251647719696.dkr.ecr.us-east-2.amazonaws.com/todo/cache:d59b97174bce710b82c453d1c61c69fabd876428b1d9b57a93fe29aaa79d6fc7... 
[36mINFO[0m[0002] No cached layer found for cmd RUN pip install --no-cache-dir -r requirements.txt 
[36mINFO[0m[0002] Unpacking rootfs as cmd RUN pip install --no-cache-dir -r requirements.txt requires it. 
[36mINFO[0m[0014] Taking snapshot of full filesystem...        
[36mINFO[0m[0020] Using files from context: [/workspace/source/requirements.txt] 
[36mINFO[0m[0020] COPY requirements.txt /usr/src/app/          
[36mINFO[0m[0020] Taking snapshot of files...                  
[36mINFO[0m[0020] RUN pip install --no-cache-dir -r requirements.txt 
[36mINFO[0m[0020] cmd: /bin/sh                                 
[36mINFO[0m[0020] args: [-c pip install --no-cache-dir -r requirements.txt] 
Collecting Flask (from -r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/9b/93/628509b8d5dc749656a9641f4caf13540e2cdec85276964ff8f43bbb1d3b/Flask-1.1.1-py2.py3-none-any.whl (94kB)
Collecting Jinja2>=2.10.1 (from Flask->-r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/27/24/4f35961e5c669e96f6559760042a55b9bcfcdb82b9bdb3c8753dbe042e35/Jinja2-2.11.1-py2.py3-none-any.whl (126kB)
Collecting itsdangerous>=0.24 (from Flask->-r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/76/ae/44b03b253d6fade317f32c24d100b3b35c2239807046a4c953c7b89fa49e/itsdangerous-1.1.0-py2.py3-none-any.whl
Collecting click>=5.1 (from Flask->-r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/fa/37/45185cb5abbc30d7257104c434fe0b07e5a195a6847506c074527aa599ec/Click-7.0-py2.py3-none-any.whl (81kB)
Collecting Werkzeug>=0.15 (from Flask->-r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/ba/a5/d6f8a6e71f15364d35678a4ec8a0186f980b3bd2545f40ad51dd26a87fb1/Werkzeug-1.0.0-py2.py3-none-any.whl (298kB)
Collecting MarkupSafe>=0.23 (from Jinja2>=2.10.1->Flask->-r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/b2/5f/23e0023be6bb885d00ffbefad2942bc51a620328ee910f64abe5a8d18dd1/MarkupSafe-1.1.1-cp36-cp36m-manylinux1_x86_64.whl
Installing collected packages: MarkupSafe, Jinja2, itsdangerous, click, Werkzeug, Flask
Successfully installed Flask-1.1.1 Jinja2-2.11.1 MarkupSafe-1.1.1 Werkzeug-1.0.0 click-7.0 itsdangerous-1.1.0
You are using pip version 10.0.1, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
[36mINFO[0m[0022] Taking snapshot of full filesystem...        
[36mINFO[0m[0025] Using files from context: [/workspace/source] 
[36mINFO[0m[0025] COPY . /usr/src/app                          
[36mINFO[0m[0025] Pushing layer 251647719696.dkr.ecr.us-east-2.amazonaws.com/todo/cache:d59b97174bce710b82c453d1c61c69fabd876428b1d9b57a93fe29aaa79d6fc7 to cache now 
[36mINFO[0m[0025] Taking snapshot of files...                  
[36mINFO[0m[0025] Using files from context: [/workspace/source/requirements.txt] 
[36mINFO[0m[0025] COPY requirements.txt .                      
[36mINFO[0m[0025] Taking snapshot of files...                  
[36mINFO[0m[0025] Using files from context: [/workspace/source/butler.png] 
[36mINFO[0m[0025] COPY butler.png .                            
[36mINFO[0m[0025] Taking snapshot of files...                  
[36mINFO[0m[0025] Using files from context: [/workspace/source/xss.html] 
[36mINFO[0m[0025] COPY xss.html .                              
[36mINFO[0m[0025] Taking snapshot of files...                  
[36mINFO[0m[0025] Using files from context: [/workspace/source/flask_app.py] 
[36mINFO[0m[0025] COPY flask_app.py .                          
[36mINFO[0m[0025] Taking snapshot of files...                  
[36mINFO[0m[0025] ENV PORT 8080                                
[36mINFO[0m[0025] No files changed in this command, skipping snapshotting. 
[36mINFO[0m[0025] EXPOSE 8080                                  
[36mINFO[0m[0025] cmd: EXPOSE                                  
[36mINFO[0m[0025] Adding exposed port: 8080/tcp                
[36mINFO[0m[0025] No files changed in this command, skipping snapshotting. 
[36mINFO[0m[0025] ENTRYPOINT ["python"]                        
[36mINFO[0m[0025] No files changed in this command, skipping snapshotting. 
[36mINFO[0m[0025] CMD ["/usr/src/app/flask_app.py"]            
[36mINFO[0m[0025] No files changed in this command, skipping snapshotting. 
[33mWARN[0m[0026] error uploading layer to cache: failed to push to destination 251647719696.dkr.ecr.us-east-2.amazonaws.com/todo/cache:d59b97174bce710b82c453d1c61c69fabd876428b1d9b57a93fe29aaa79d6fc7: NAME_UNKNOWN: The repository with name 'todo/cache' does not exist in the registry with id '251647719696' 
2020/02/17 17:23:42 existing blob: sha256:490280dbcfb772eb5731f059e38fcfacaeb75b4d005af7c249fd51926db2bd62
2020/02/17 17:23:42 existing blob: sha256:ece825d3308bbf98f708d95475ccd880497a1e2979ff4ef2534d49049a18488f
2020/02/17 17:23:42 existing blob: sha256:e10b68fb77e6e91453cd4c1b02e2d77aa23a857cd8eb250617129d074478e1a5
2020/02/17 17:23:42 existing blob: sha256:2d21c767035c4593de8bf7ad9781aa83ba110871d1a50871192f4e3480e6f11d
2020/02/17 17:23:42 existing blob: sha256:f0db43b9b8da254cebc77bf871006df01219e195b9853616b9f708f124a00f3a
2020/02/17 17:23:42 existing blob: sha256:06854774e2f35e4763103a446112c67322913a6177bea69eb49663e0166e6d6d
2020/02/17 17:23:42 existing blob: sha256:e96bc319bce0351d1157092352bc5f85f8800c745388e60e86d06dec99285b45
2020/02/17 17:23:42 existing blob: sha256:e2c0fb34dff3a1d32346b92e53fb88a14d1987b402a2348cb379c039687fabe2
2020/02/17 17:23:42 existing blob: sha256:1c7fe136a31e13a1c879245672184ced3b9fc590989ba42a522a57b071a9c1aa
2020/02/17 17:23:42 pushed blob: sha256:4a3dc09c03bc11e7ac108e68b44844b80c46465daf5c2781fb294c44c9f4ea85
2020/02/17 17:23:42 pushed blob: sha256:b2dd0d81d2d57fab701b5b0d18b9f59e69fe55f67f09ef77fa124c32bdf8dd55
2020/02/17 17:23:42 pushed blob: sha256:366cf13521e16e5f97ffa8119fd25fbf21b9a45aeca08778d80fd82ea3c1445e
2020/02/17 17:23:42 pushed blob: sha256:501237ce2aa4dc0cc55c6480fd812f118184687874db02ae0444a03399a75d8e
2020/02/17 17:23:42 pushed blob: sha256:7fe4a562a731f23fac95ade924078977273e3a31010a5f6e6d9ffb67eb42d43d
2020/02/17 17:23:42 pushed blob: sha256:253c73ea187b397ff329b5ff3ac285bed83695ca4ae8678ffdbbe024aa868fcd
2020/02/17 17:23:43 pushed blob: sha256:d6ac0eff6a51833330d9b619b0106b6c3699d2fd2398ccfb8f3149fed35f01e4
2020/02/17 17:23:43 pushed blob: sha256:be8ce11be8dc8495aa67586ba4f0543780b6e62406b6a2a9428c693db2ffe95e
2020/02/17 17:23:43 251647719696.dkr.ecr.us-east-2.amazonaws.com/*******/flask-**-sample:0.0.0-SNAPSHOT-PR-14-2: digest: sha256:c2435f28ecf5bdb33c5ac59996dff2cdcd5e9c25ecfe3fa9ebe6431620b71712 size: 2867

Showing logs for build [32mtrietlu-flask-jx-sample-pr-14-s-czzwj-2[0m stage [32mfrom-build-pack[0m and container [32mstep-postbuild-post-build[0m
no CVE provider running in the current ** namespace so skip adding image to be analysed

Showing logs for build [32mtrietlu-flask-jx-sample-pr-14-s-czzwj-2[0m stage [32mfrom-build-pack[0m and container [32mstep-postbuild-container-image-scan[0m
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip3 install --user` instead.
Collecting boto3
  Downloading https://files.pythonhosted.org/packages/73/c1/c25300e0afbe36f550d82affc0d1705076e9ea909ef33e8dd1f7147df10b/boto3-1.12.0-py2.py3-none-any.whl (128kB)
Collecting botocore<1.16.0,>=1.15.0 (from boto3)
  Downloading https://files.pythonhosted.org/packages/a4/ba/236f25b9200f0cda4842585205b566979484d38927a8a302cc5c1beea10c/botocore-1.15.0-py2.py3-none-any.whl (5.9MB)
Collecting s3transfer<0.4.0,>=0.3.0 (from boto3)
  Downloading https://files.pythonhosted.org/packages/69/79/e6afb3d8b0b4e96cefbdc690f741d7dd24547ff1f94240c997a26fa908d3/s3transfer-0.3.3-py2.py3-none-any.whl (69kB)
Collecting jmespath<1.0.0,>=0.7.1 (from boto3)
  Downloading https://files.pythonhosted.org/packages/83/94/7179c3832a6d45b266ddb2aac329e101367fbdb11f425f13771d27f225bb/jmespath-0.9.4-py2.py3-none-any.whl
Collecting python-dateutil<3.0.0,>=2.1 (from botocore<1.16.0,>=1.15.0->boto3)
  Downloading https://files.pythonhosted.org/packages/d4/70/d60450c3dd48ef87586924207ae8907090de0b306af2bce5d134d78615cb/python_dateutil-2.8.1-py2.py3-none-any.whl (227kB)
Collecting urllib3<1.26,>=1.20; python_version != "3.4" (from botocore<1.16.0,>=1.15.0->boto3)
  Downloading https://files.pythonhosted.org/packages/e8/74/6e4f91745020f967d09332bb2b8b9b10090957334692eb88ea4afe91b77f/urllib3-1.25.8-py2.py3-none-any.whl (125kB)
Collecting docutils<0.16,>=0.10 (from botocore<1.16.0,>=1.15.0->boto3)
  Downloading https://files.pythonhosted.org/packages/22/cd/a6aa959dca619918ccb55023b4cb151949c64d4d5d55b3f4ffd7eee0c6e8/docutils-0.15.2-py3-none-any.whl (547kB)
Collecting six>=1.5 (from python-dateutil<3.0.0,>=2.1->botocore<1.16.0,>=1.15.0->boto3)
  Downloading https://files.pythonhosted.org/packages/65/eb/1f97cb97bfc2390a276969c6fae16075da282f5058082d4cb10c6c5c1dba/six-1.14.0-py2.py3-none-any.whl
Installing collected packages: six, python-dateutil, jmespath, urllib3, docutils, botocore, s3transfer, boto3
Successfully installed boto3-1.12.0 botocore-1.15.0 docutils-0.15.2 jmespath-0.9.4 python-dateutil-2.8.1 s3transfer-0.3.3 six-1.14.0 urllib3-1.25.8
Doing CVE scan of *******/flask-**-sample:0.0.0-SNAPSHOT-PR-14-2 in registry 251647719696.dkr.ecr.us-east-2.amazonaws.com
CVE findings failed by policy
{'HIGH': 124, 'MEDIUM': 369, 'INFORMATIONAL': 390, 'LOW': 295, 'CRITICAL': 23, 'UNDEFINED': 5}
[31m
Pipeline failed on stage 'from-build-pack' : container 'step-postbuild-container-image-scan'. The execution of the pipeline has stopped.[0m
