
Showing logs for build [32mtrietlu-flask-jx-sample-pr-13-s-6jwfv-2[0m stage [32mfrom-build-pack[0m and container [32mstep-credential-initializer-9fpfc[0m
{"level":"warn","ts":1581736492.8725436,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"ref: refs/heads/0.8.0-**-support-backwards-incompats\" is not a valid GitHub commit ID"}
{"level":"info","ts":1581736492.8730772,"logger":"fallback-logger","caller":"creds-init/main.go:40","msg":"Credentials initialized."}

Showing logs for build [32mtrietlu-flask-jx-sample-pr-13-s-6jwfv-2[0m stage [32mfrom-build-pack[0m and container [32mstep-working-dir-initializer-wzqn9[0m
{"level":"warn","ts":1581736493.826075,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/HEAD: no such file or directory"}
{"level":"info","ts":1581736493.8276849,"logger":"fallback-logger","caller":"bash/main.go:64","msg":"Successfully executed command \"sh -c mkdir -p /workspace/source\"; output "}

Showing logs for build [32mtrietlu-flask-jx-sample-pr-13-s-6jwfv-2[0m stage [32mfrom-build-pack[0m and container [32mstep-place-tools[0m

Showing logs for build [32mtrietlu-flask-jx-sample-pr-13-s-6jwfv-2[0m stage [32mfrom-build-pack[0m and container [32mstep-git-source-trietlu-flask-jx-sample-pr-13-s-6jwfv-fjgp4[0m
{"level":"warn","ts":1581736498.889975,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"ref: refs/heads/0.8.0-**-support-backwards-incompats\" is not a valid GitHub commit ID"}
{"level":"info","ts":1581736499.1933653,"logger":"fallback-logger","caller":"git/git.go:103","msg":"Successfully cloned https://github.com/*******/flask-**-sample.git @ master in path /workspace/source"}

Showing logs for build [32mtrietlu-flask-jx-sample-pr-13-s-6jwfv-2[0m stage [32mfrom-build-pack[0m and container [32mstep-git-merge[0m
Using SHAs from PULL_REFS=master:b239659c811a52147f43f6e08b2e3075a619b08b,13:929d0118bbd90ffad648b7042f74b4eafcfa2af2
DEBUG: LC_ALL=C JX_LOG_LEVEL=error git fetch origin --unshallow 929d0118bbd90ffad648b7042f74b4eafcfa2af2: b239659c811a52147f43f6e08b2e3075a619b08b:
DEBUG: ran git fetch --unshallow origin 929d0118bbd90ffad648b7042f74b4eafcfa2af2: b239659c811a52147f43f6e08b2e3075a619b08b: in 
DEBUG: LC_ALL=C JX_LOG_LEVEL=error git branch
DEBUG: LC_ALL=C JX_LOG_LEVEL=error git checkout master
DEBUG: ran git checkout master in 
DEBUG: LC_ALL=C JX_LOG_LEVEL=error git reset --hard b239659c811a52147f43f6e08b2e3075a619b08b
DEBUG: ran git reset --hard b239659c811a52147f43f6e08b2e3075a619b08b in 
DEBUG: LC_ALL=C JX_LOG_LEVEL=error git clean -fd .
DEBUG: ran clean --force -d . in 
DEBUG: LC_ALL=C JX_LOG_LEVEL=error git merge 929d0118bbd90ffad648b7042f74b4eafcfa2af2
DEBUG: ran git merge 929d0118bbd90ffad648b7042f74b4eafcfa2af2 in 
DEBUG: LC_ALL=C JX_LOG_LEVEL=error git log --format=%H%x1f%an%x1f%ae%x1f%cn%x1f%ce%x1f%s%n%b%x1e b239659c811a52147f43f6e08b2e3075a619b08b..HEAD
Merged SHA 929d0118bbd90ffad648b7042f74b4eafcfa2af2 with commit message 'Update flask_app.py' into base branch master
Merged SHA 21b434ab973385f35157c36f2d160cc51c590243 with commit message 'Update flask_app.py' into base branch master

Showing logs for build [32mtrietlu-flask-jx-sample-pr-13-s-6jwfv-2[0m stage [32mfrom-build-pack[0m and container [32mstep-build-code-scan[0m
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip3 install --user` instead.
Collecting python-taint
  Downloading https://files.pythonhosted.org/packages/5c/79/5b70d3299cb7dea63e2b015651c5c7507d723911ff2837e104ebd7079491/python_taint-0.42-py3-none-any.whl (52kB)
Installing collected packages: python-taint
Successfully installed python-taint-0.42
No vulnerabilities found.

Showing logs for build [32mtrietlu-flask-jx-sample-pr-13-s-6jwfv-2[0m stage [32mfrom-build-pack[0m and container [32mstep-build-python-unittest[0m

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK

Showing logs for build [32mtrietlu-flask-jx-sample-pr-13-s-6jwfv-2[0m stage [32mfrom-build-pack[0m and container [32mstep-build-container-build[0m
[36mINFO[0m[0000] Downloading base image python:onbuild        
[36mINFO[0m[0000] Error while retrieving image from cache: getting file info: stat /workspace/sha256:43780a8431c53f4afd734ad795e03127c0c607337a60639c5903a51a03535c22: no such file or directory 
[36mINFO[0m[0000] Downloading base image python:onbuild        
[36mINFO[0m[0000] Executing 3 build triggers                   
[36mINFO[0m[0000] Using files from context: [/workspace/source/requirements.txt] 
[36mINFO[0m[0000] Checking for cached layer 251647719696.dkr.ecr.us-east-2.amazonaws.com/todo/cache:d59b97174bce710b82c453d1c61c69fabd876428b1d9b57a93fe29aaa79d6fc7... 
[36mINFO[0m[0000] No cached layer found for cmd RUN pip install --no-cache-dir -r requirements.txt 
[36mINFO[0m[0000] Unpacking rootfs as cmd RUN pip install --no-cache-dir -r requirements.txt requires it. 
[36mINFO[0m[0013] Taking snapshot of full filesystem...        
[36mINFO[0m[0017] Using files from context: [/workspace/source/requirements.txt] 
[36mINFO[0m[0017] COPY requirements.txt /usr/src/app/          
[36mINFO[0m[0017] Taking snapshot of files...                  
[36mINFO[0m[0017] RUN pip install --no-cache-dir -r requirements.txt 
[36mINFO[0m[0017] cmd: /bin/sh                                 
[36mINFO[0m[0017] args: [-c pip install --no-cache-dir -r requirements.txt] 
Collecting Flask (from -r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/9b/93/628509b8d5dc749656a9641f4caf13540e2cdec85276964ff8f43bbb1d3b/Flask-1.1.1-py2.py3-none-any.whl (94kB)
Collecting itsdangerous>=0.24 (from Flask->-r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/76/ae/44b03b253d6fade317f32c24d100b3b35c2239807046a4c953c7b89fa49e/itsdangerous-1.1.0-py2.py3-none-any.whl
Collecting Jinja2>=2.10.1 (from Flask->-r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/27/24/4f35961e5c669e96f6559760042a55b9bcfcdb82b9bdb3c8753dbe042e35/Jinja2-2.11.1-py2.py3-none-any.whl (126kB)
Collecting Werkzeug>=0.15 (from Flask->-r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/ba/a5/d6f8a6e71f15364d35678a4ec8a0186f980b3bd2545f40ad51dd26a87fb1/Werkzeug-1.0.0-py2.py3-none-any.whl (298kB)
Collecting click>=5.1 (from Flask->-r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/fa/37/45185cb5abbc30d7257104c434fe0b07e5a195a6847506c074527aa599ec/Click-7.0-py2.py3-none-any.whl (81kB)
Collecting MarkupSafe>=0.23 (from Jinja2>=2.10.1->Flask->-r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/b2/5f/23e0023be6bb885d00ffbefad2942bc51a620328ee910f64abe5a8d18dd1/MarkupSafe-1.1.1-cp36-cp36m-manylinux1_x86_64.whl
Installing collected packages: itsdangerous, MarkupSafe, Jinja2, Werkzeug, click, Flask
Successfully installed Flask-1.1.1 Jinja2-2.11.1 MarkupSafe-1.1.1 Werkzeug-1.0.0 click-7.0 itsdangerous-1.1.0
You are using pip version 10.0.1, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
[36mINFO[0m[0019] Taking snapshot of full filesystem...        
[36mINFO[0m[0022] Using files from context: [/workspace/source] 
[36mINFO[0m[0022] Pushing layer 251647719696.dkr.ecr.us-east-2.amazonaws.com/todo/cache:d59b97174bce710b82c453d1c61c69fabd876428b1d9b57a93fe29aaa79d6fc7 to cache now 
[36mINFO[0m[0022] COPY . /usr/src/app                          
[36mINFO[0m[0022] Taking snapshot of files...                  
[36mINFO[0m[0023] Using files from context: [/workspace/source/requirements.txt] 
[36mINFO[0m[0023] COPY requirements.txt .                      
[36mINFO[0m[0023] Taking snapshot of files...                  
[36mINFO[0m[0023] Using files from context: [/workspace/source/butler.png] 
[36mINFO[0m[0023] COPY butler.png .                            
[36mINFO[0m[0023] Taking snapshot of files...                  
[36mINFO[0m[0023] Using files from context: [/workspace/source/xss.html] 
[36mINFO[0m[0023] COPY xss.html .                              
[36mINFO[0m[0023] Taking snapshot of files...                  
[36mINFO[0m[0023] Using files from context: [/workspace/source/flask_app.py] 
[36mINFO[0m[0023] COPY flask_app.py .                          
[36mINFO[0m[0023] Taking snapshot of files...                  
[36mINFO[0m[0023] ENV PORT 8080                                
[36mINFO[0m[0023] No files changed in this command, skipping snapshotting. 
[36mINFO[0m[0023] EXPOSE 8080                                  
[36mINFO[0m[0023] cmd: EXPOSE                                  
[36mINFO[0m[0023] Adding exposed port: 8080/tcp                
[36mINFO[0m[0023] No files changed in this command, skipping snapshotting. 
[36mINFO[0m[0023] ENTRYPOINT ["python"]                        
[36mINFO[0m[0023] No files changed in this command, skipping snapshotting. 
[36mINFO[0m[0023] CMD ["/usr/src/app/flask_app.py"]            
[36mINFO[0m[0023] No files changed in this command, skipping snapshotting. 
[33mWARN[0m[0023] error uploading layer to cache: failed to push to destination 251647719696.dkr.ecr.us-east-2.amazonaws.com/todo/cache:d59b97174bce710b82c453d1c61c69fabd876428b1d9b57a93fe29aaa79d6fc7: NAME_UNKNOWN: The repository with name 'todo/cache' does not exist in the registry with id '251647719696' 
2020/02/15 03:15:25 existing blob: sha256:e96bc319bce0351d1157092352bc5f85f8800c745388e60e86d06dec99285b45
2020/02/15 03:15:25 existing blob: sha256:f0db43b9b8da254cebc77bf871006df01219e195b9853616b9f708f124a00f3a
2020/02/15 03:15:25 existing blob: sha256:e10b68fb77e6e91453cd4c1b02e2d77aa23a857cd8eb250617129d074478e1a5
2020/02/15 03:15:25 existing blob: sha256:1c7fe136a31e13a1c879245672184ced3b9fc590989ba42a522a57b071a9c1aa
2020/02/15 03:15:25 existing blob: sha256:06854774e2f35e4763103a446112c67322913a6177bea69eb49663e0166e6d6d
2020/02/15 03:15:25 existing blob: sha256:2d21c767035c4593de8bf7ad9781aa83ba110871d1a50871192f4e3480e6f11d
2020/02/15 03:15:25 existing blob: sha256:e2c0fb34dff3a1d32346b92e53fb88a14d1987b402a2348cb379c039687fabe2
2020/02/15 03:15:25 existing blob: sha256:ece825d3308bbf98f708d95475ccd880497a1e2979ff4ef2534d49049a18488f
2020/02/15 03:15:25 existing blob: sha256:490280dbcfb772eb5731f059e38fcfacaeb75b4d005af7c249fd51926db2bd62
2020/02/15 03:15:25 pushed blob: sha256:d8a5484a2495712aa8593a2b777a319eddfaf5354ac4c83f02c069a52cb7cb12
2020/02/15 03:15:26 pushed blob: sha256:66420367f85271e1ba61cd09c4b4dc589391508875779e1d2f76ee4e3361bbe9
2020/02/15 03:15:26 pushed blob: sha256:5c59a8fe410fc44390173d32ac447765dc16bd9b915be64da15c04877bb8215f
2020/02/15 03:15:26 pushed blob: sha256:5015e8a90cee48b6a20cedf726522d22c85e89a62a95468ebe968e2aa61ad6a5
2020/02/15 03:15:26 pushed blob: sha256:7da77e86be363114f4052357baa80a0560a93be8d928b774e6fac9857dc3d719
2020/02/15 03:15:26 pushed blob: sha256:7898aabafbaf872da7a2ae56bbd8600ec85941a0757dcf5456feec6ed9e2fc11
2020/02/15 03:15:26 pushed blob: sha256:0525112820c8a6ab1bb76c6defe5bad88b06cb59094dafa3288191120280699f
2020/02/15 03:15:26 pushed blob: sha256:0f6d1459644a15472c4fa2720a7fa2d0fa2a897149b615416468f788b9474df7
2020/02/15 03:15:26 251647719696.dkr.ecr.us-east-2.amazonaws.com/*******/flask-**-sample:0.0.0-SNAPSHOT-PR-13-2: digest: sha256:33f6c94d6007d5eede5872b3f21b2a1f6bdb5ab3277079e758234f51b8c54fa9 size: 2867

Showing logs for build [32mtrietlu-flask-jx-sample-pr-13-s-6jwfv-2[0m stage [32mfrom-build-pack[0m and container [32mstep-postbuild-post-build[0m
no CVE provider running in the current ** namespace so skip adding image to be analysed

Showing logs for build [32mtrietlu-flask-jx-sample-pr-13-s-6jwfv-2[0m stage [32mfrom-build-pack[0m and container [32mstep-postbuild-container-image-scan[0m
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip3 install --user` instead.
Collecting boto3
  Downloading https://files.pythonhosted.org/packages/73/c1/c25300e0afbe36f550d82affc0d1705076e9ea909ef33e8dd1f7147df10b/boto3-1.12.0-py2.py3-none-any.whl (128kB)
Collecting botocore<1.16.0,>=1.15.0 (from boto3)
  Downloading https://files.pythonhosted.org/packages/a4/ba/236f25b9200f0cda4842585205b566979484d38927a8a302cc5c1beea10c/botocore-1.15.0-py2.py3-none-any.whl (5.9MB)
Collecting s3transfer<0.4.0,>=0.3.0 (from boto3)
  Downloading https://files.pythonhosted.org/packages/69/79/e6afb3d8b0b4e96cefbdc690f741d7dd24547ff1f94240c997a26fa908d3/s3transfer-0.3.3-py2.py3-none-any.whl (69kB)
Collecting jmespath<1.0.0,>=0.7.1 (from boto3)
  Downloading https://files.pythonhosted.org/packages/83/94/7179c3832a6d45b266ddb2aac329e101367fbdb11f425f13771d27f225bb/jmespath-0.9.4-py2.py3-none-any.whl
Collecting urllib3<1.26,>=1.20; python_version != "3.4" (from botocore<1.16.0,>=1.15.0->boto3)
  Downloading https://files.pythonhosted.org/packages/e8/74/6e4f91745020f967d09332bb2b8b9b10090957334692eb88ea4afe91b77f/urllib3-1.25.8-py2.py3-none-any.whl (125kB)
Collecting python-dateutil<3.0.0,>=2.1 (from botocore<1.16.0,>=1.15.0->boto3)
  Downloading https://files.pythonhosted.org/packages/d4/70/d60450c3dd48ef87586924207ae8907090de0b306af2bce5d134d78615cb/python_dateutil-2.8.1-py2.py3-none-any.whl (227kB)
Collecting docutils<0.16,>=0.10 (from botocore<1.16.0,>=1.15.0->boto3)
  Downloading https://files.pythonhosted.org/packages/22/cd/a6aa959dca619918ccb55023b4cb151949c64d4d5d55b3f4ffd7eee0c6e8/docutils-0.15.2-py3-none-any.whl (547kB)
Collecting six>=1.5 (from python-dateutil<3.0.0,>=2.1->botocore<1.16.0,>=1.15.0->boto3)
  Downloading https://files.pythonhosted.org/packages/65/eb/1f97cb97bfc2390a276969c6fae16075da282f5058082d4cb10c6c5c1dba/six-1.14.0-py2.py3-none-any.whl
Installing collected packages: jmespath, urllib3, six, python-dateutil, docutils, botocore, s3transfer, boto3
Successfully installed boto3-1.12.0 botocore-1.15.0 docutils-0.15.2 jmespath-0.9.4 python-dateutil-2.8.1 s3transfer-0.3.3 six-1.14.0 urllib3-1.25.8
Doing CVE scan of *******/flask-**-sample:0.0.0-SNAPSHOT-PR-13-2 in registry 251647719696.dkr.ecr.us-east-2.amazonaws.com
CVE findings failed by policy
{'HIGH': 124, 'MEDIUM': 369, 'INFORMATIONAL': 390, 'LOW': 295, 'CRITICAL': 23, 'UNDEFINED': 5}
[31m
Pipeline failed on stage 'from-build-pack' : container 'step-postbuild-container-image-scan'. The execution of the pipeline has stopped.[0m
